// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acrvymqsczclwzakpkip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjcnZ5bXFzY3pjbHd6YWtwa2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODQ4NTcsImV4cCI6MjA3Nzg2MDg1N30.uHccf32IxPnTP2aGQO9V9KKMDfgGn7CMCasM0TyuVMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});